name: Documentation Issue
description: Report an issue with the documentation
labels: documentation
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the issue
          description: Clearly explain what is missing or needs to be changed.
      validations:
          required: true

    - type: input
      id: link
      attributes:
          label: Documentation Link
          description: If applicable, provide a link to where the issue can currently be observed.
