blank_issues_enabled: false
contact_links:
    - name: Join our Discord server
      url: https://discord.gg/rdce5GXRrC
      about: Fastest way to get help and support!
    - name: Check out our Documentation
      url: https://docs.rubato.app/latest/api/
      about: You're issue may be explained somewhere!
